name: Deploy API to Azure Functions

on:
  push:
    branches: ["master"]
    paths:
      - "api/**"
      - ".github/workflows/api-deploy.yml"
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: selfdb-music-app-api
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./api"
  DOTNET_VERSION: "8.0.x"

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
