name: Deploy API to Azure Functions

on:
  push:
    branches:
      - main # ← main に push されたときにデプロイ

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Restore dependencies
        run: dotnet restore ./api

      - name: Build
        run: dotnet build ./api --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./api --configuration Release --output ./publish

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: ./publish
